### ISSUE TITLE
Plugin error whenever development server re-started

### ISSUE THREAD

**Issue by Ameobea** [leolabs/gatsby-source-spotify#46] opened 2021-12-28 21:39 UTC
Everything works fine the first time, and running `gatsby clean` fixes it.  Perhaps some kind of cache corruption or similar.

`gatsby` version: 4.4
`gatsby-source-spotify` version: 2.0

Here is the error:

```
 ERROR #11321  PLUGIN

"gatsby-source-spotify" threw an error while running the sourceNodes lifecycle:

Cannot read properties of undefined (reading 'type')


  TypeError: Cannot read properties of undefined (reading 'type')

  - public.js:892 Object.actions.touchNode
    [homepage]/[gatsby]/src/redux/actions/public.js:892:41

  - call-deferred-api.ts:17 callRealApi
    [homepage]/[gatsby]/src/utils/call-deferred-api.ts:17:20

  - actions.ts:26 callApi
    [homepage]/[gatsby]/src/state-machines/develop/actions.ts:26:6

  - interpreter.js:767 Interpreter.exec
    [homepage]/[xstate]/lib/interpreter.js:767:16

  - interpreter.js:204 Interpreter.execute
    [homepage]/[xstate]/lib/interpreter.js:204:14

  - interpreter.js:230 Interpreter.update
    [homepage]/[xstate]/lib/interpreter.js:230:12

  - interpreter.js:110
    [homepage]/[xstate]/lib/interpreter.js:110:15

  - scheduler.js:69 Scheduler.process
    [homepage]/[xstate]/lib/scheduler.js:69:7

  - scheduler.js:48 Scheduler.schedule
    [homepage]/[xstate]/lib/scheduler.js:48:10

  - interpreter.js:104 Interpreter.send
    [homepage]/[xstate]/lib/interpreter.js:104:23

  - interpreter.js:1105 callback
    [homepage]/[xstate]/lib/interpreter.js:1105:13

  - listen-for-mutations.ts:6 callback
    [homepage]/[gatsby]/src/services/listen-for-mutations.ts:6:5

  - mett.ts:44 forEach
    [homepage]/[gatsby]/src/utils/mett.ts:44:11

  - Set.forEach

  - mett.ts:43 Object.emit
    [homepage]/[gatsby]/src/utils/mett.ts:43:17

  - api-runner-node.js:120
    [homepage]/[gatsby]/src/utils/api-runner-node.js:120:20
```

I admit that this may be the result of some other plugin or gatsby config setting.  However, the behavior is entirely reproducible across every reload as far as I can tell.

**Comment by Ameobea** [comment] 2021-12-29 04:32
After wasting significantly more time on the gatsby site using this plugin, I'm beginning to think more and more that this is the fault of some other plugin.  You can just close this issue if you think so as well; I know that there isn't much utility here for a repro or similar.

**Comment by leolabs** [comment] 2021-12-30 15:20
Thank you for your report! If you think this is caused by another plugin, then it might be a good idea to close this issue. If you find anything that might be caused by this plugin, feel free to open a new issue :)

**Closed as completed by leolabs** 2021-12-30 15:20 UTC
